[package]
name = "scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
serde.workspace = true
rand.workspace = true
serde_json.workspace = true
filter.workspace = true
indexify_internal_api.workspace = true

